# -*- coding: utf-8 -*-
"""AverageFromInputFileLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLNSFv6rlzpFfTli5I21fDfC9tfv3xbe
"""

def main():
  numberofnumber = int(input('Please enter the number of number you want:'))
  infile = open("number.txt","w")
  i = 0
  while numberofnumber != 0:
    number = input("Enter a number :")
    infile.write(f'{number}\n')
    numberofnumber = numberofnumber - 1
  infile.close()

if __name__ == '__main__':
  main()

def main():
    filename = "number.txt"
    try:
        values = read_values_from_file(filename)
        if values:
            avg = calculate_average(values)
            print_average(avg)
        else:
            print("No valid numbers were found in the file.")
    except Exception as e:
        print(f"An error occurred: {e}")

def read_values_from_file(filename):
    values = []
    try:
        with open(filename, 'r') as file:
            for line in file:
                try:
                    number = float(line.strip())
                    values.append(number)
                except ValueError:
                    print(f"Skipping invalid value: {line.strip()}")
    except FileNotFoundError:
        print(f"File {filename} not found.")
        raise
    return values

def calculate_average(values):
    return sum(values) / len(values)

def print_average(avg):
    print(f"The average is: {avg}")

if __name__ == "__main__":
    main()