# -*- coding: utf-8 -*-
"""FilesandExceptionsLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmtkVDQ0xhhSB9J-KsRsCbwRJIK6kLYM
"""

def main():
  numberofnumber = int(input('Please enter the number of number you want:'))
  infile = open("number.txt","w")
  i = 0
  while numberofnumber != 0:
    number = input("Enter a number :")
    infile.write(f'{number}\n')
    numberofnumber = numberofnumber - 1
  infile.close()

if __name__ == '__main__':
  main()

emp_file = open("number.txt","r")
number = emp_file.readline()
List_number = []
while number != '':
  number = number.rstrip('\n')
  List_number.append(int(number))
  number = emp_file.readline()
emp_file.close()
print("The numbers are:",List_number)
j = 0
for i in List_number:
  j = j + i
print("Their total is:",j)

def main():
  infile = open("employees.txt","w")
  number_employe = int(input("The number of employe is :"))
  while number_employe != 0:
    name = input("Enter a name :")
    id_num = int(input("Enter an id number :"))
    dept = input("Enter a departement :")
    infile.write(f'{name}\n')
    infile.write(f'{str(id_num)}\n')
    infile.write(f'{dept}\n')
    number_employe = number_employe - 1
  infile.close()

if __name__ == '__main__':
  main()