# -*- coding: utf-8 -*-
"""Try-CatchLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4fdspaHfNPzlBzEnRdwduebxR21Y3g1
"""

#Try Catch Exercise:

def main():
  infile = open("employees.txt","w")
  number_employe = int(input("The number of employe is :"))
  while number_employe != 0:
    name = input("Enter a name :")
    id_num = int(input("Enter an id number :"))
    dept = input("Enter a departure date :")
    infile.write(f'{name}\n')
    infile.write(f'{str(id_num)}\n')
    infile.write(f'{dept}\n')
    number_employe = number_employe - 1
  infile.close()

if __name__ == '__main__':
  main()

def read_file_and_search_term(file_path, search_term):
    try:
        with open(file_path, 'r') as file:
            content = file.read()
        if search_term not in content:
            raise Exception(f"'{search_term}' not found in the file.")
        print("File read successfully.")
        print("File content:")
        print(content)
    except FileNotFoundError:
        print(f"Error: No such file or directory:'{file_path}'. The file has been closed.")
    except IsADirectoryError:
        print(f"Error: Expected a file but found a directory: '{file_path}'.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

file_path = input("Enter the file path: ")
search_term = input("Enter the search term: ")
read_file_and_search_term(file_path, search_term)